version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu
  - source: ./build/libs/root.war
    destination: /var/lib/tomcat7/webapps

hooks:
  AfterInstall:
   - location: ./restartTomcat.sh
     timeout: 180
     runas: ubuntu